CREATE TABLE IF NOT EXISTS restaurants (
  id INT NOT NULL AUTO_INCREMENT,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  latitude DECIMAL(8,6),
  longitude DECIMAL(9,6),
  image_url TEXT NOT NULL,
  description TEXT NOT NULL,
  added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id)
);
